### ISSUE TITLE
Doesn't compile on clang 16.0.6 due to issue in sentencepiece

### ISSUE THREAD

**Issue by XapaJIaMnu** [marian-nmt/marian-dev#1006]
### Bug description
```
[build] marian-dev/src/3rd_party/sentencepiece/src/trainer_interface.cc:212:7: error: integer value -1 is outside the valid range of values [0, 255] for this enumeration type [-Wenum-constexpr-conversion]
[build]       static_cast<unicode_script::ScriptType>(-1);
[build]       ^
[build] 1 error generated.
```
