### ISSUE TITLE
marian-server fails to compile with boost 1.66

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#156]
It seems the simple-websocket-server is not compatible with boost 1.66. This might require a solution of `#ifdef` to maintain backward compatibility.

```
In file included from /home/marcinjd/marian-dev/src/command/marian_server.cpp:5:0:
/home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp:181:7: error: invalid use of template-name ‘boost::asio::strand’ without an argument list
       asio::strand strand;
       ^
In file included from /home/marcinjd/marian-dev/src/command/marian_server.cpp:5:0:
/home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp: In constructor ‘SimpleWeb::SocketServerBase<socket_type>::Connection::Connection(std::unique_ptr<T>&&)’:
/home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp:93:112: error: class ‘SimpleWeb::SocketServerBase<socket_type>::Connection’ does not have any field named ‘strand’
       Connection(std::unique_ptr<socket_type> &&socket) noexcept : socket(std::move(socket)), timeout_idle(0), strand(this->socket->get_io_service()), closed(false) {}
                                                                                                                ^
In file included from /home/marcinjd/marian-dev/src/command/marian_server.cpp:5:0:
/home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp: In constructor ‘SimpleWeb::SocketServerBase<socket_type>::Connection::Connection(std::shared_ptr<SimpleWeb::ScopeRunner>, long int, Args&& ...)’:
/home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp:107:138: error: class ‘SimpleWeb::SocketServerBase<socket_type>::Connection’ does not have any field named ‘strand’
           : handler_runner(std::move(handler_runner)), socket(new socket_type(std::forward<Args>(args)...)), timeout_idle(timeout_idle), strand(socket->get_io_service()), closed(false) {}
                                                                                                                                          ^
/home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp: In member function ‘void SimpleWeb::SocketServerBase<socket_type>::Connection::send_from_queue()’:
/home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp:197:9: error: ‘strand’ was not declared in this scope
         strand.post([self]() {
         ^
/home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp:197:9: note: suggested alternative:
In file included from /usr/local/include/boost/asio.hpp:123:0,
                 from /home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp:45,
                 from /home/marcinjd/marian-dev/src/command/marian_server.cpp:5:
/usr/local/include/boost/asio/strand.hpp:29:7: note:   ‘boost::asio::strand’
 class strand
       ^
In file included from /home/marcinjd/marian-dev/src/command/marian_server.cpp:5:0:
/home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp: In member function ‘void SimpleWeb::SocketServerBase<socket_type>::Connection::send(const std::shared_ptr<SimpleWeb::SocketServerBase<socket_type>::SendStream>&, const std::function<void(const boost::system::error_code&)>&, unsigned char)’:
/home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp:272:9: error: ‘strand’ was not declared in this scope
         strand.post([self, header_stream, message_stream, callback]() {
         ^
/home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp:272:9: note: suggested alternative:
In file included from /usr/local/include/boost/asio.hpp:123:0,
                 from /home/marcinjd/marian-dev/src/3rd_party/simple-websocket-server/server_ws.hpp:45,
                 from /home/marcinjd/marian-dev/src/command/marian_server.cpp:5:
/usr/local/include/boost/asio/strand.hpp:29:7: note:   ‘boost::asio::strand’
 class strand
       ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-gpu-targets’
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-gpu-targets’
src/CMakeFiles/marian_server.dir/build.make:62: recipe for target 'src/CMakeFiles/marian_server.dir/command/marian_server.cpp.o' failed
make[2]: *** [src/CMakeFiles/marian_server.dir/command/marian_server.cpp.o] Error 1
CMakeFiles/Makefile2:100: recipe for target 'src/CMakeFiles/marian_server.dir/all' failed
make[1]: *** [src/CMakeFiles/marian_server.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by snukky** [comment]
As a beginning I've added a new CMake option to turn off the compilation of marian-server, e.g.:

    cmake .. -DCOMPILE_SERVER=OFF

Is the problem with `boost::asio` the only one you get compiling with Boost 1.66? I'm getting more errors similar to that one when I use manually compiled Boost:

    /home/user/codes/boost_1_66_0/lib64/include/boost/system/error_code.hpp(253): 
        error: exception specification for virtual function 
        "boost::system::error_category::std_category::equivalent(const std::error_code &, int) const" 
        is incompatible with that of overridden function 
        "std::_V2::error_category::equivalent(const std::error_code &, int) const"
 
Have you encountered them too?
I have no issues with manually compiled Boost 1.58 and 1.64.

**Comment by snukky** [comment]
It seems to be solved after updating Simple-WebSocket-Server, but confirm that, please.
WWSS may use StandaloneAsio instead of Boost::Asio, which we may keep in the repo as a 3rd party library to avoid such kind of issues in future.
