### ISSUE TITLE
Compilation fails on macOS when Xcode 12.5 is installed

### ISSUE THREAD

**Issue by tmacwill** [marian-nmt/marian-dev#871]
### Bug description

Marian compilation fails on macOS with Xcode 12.5 (the latest stable version) command-line tools, but succeeds with Xcode 12.4.

There appear to be two categories of errors:

```
In file included from /Users/serenade/marian-dev/src/3rd_party/sentencepiece/third_party/protobuf-lite/arena.cc:31:
In file included from /Users/serenade/marian-dev/src/3rd_party/sentencepiece/src/../third_party/protobuf-lite/google/protobuf/arena.h:36:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/limits:105:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/type_traits:417:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/cstddef:37:
/Users/serenade/marian-dev/src/3rd_party/sentencepiece/version:1:1: error: expected unqualified-id
0.1.94
```

and

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/atomic:1854:21: error: unknown type name 'ptrdiff_t'
    _Tp* operator-=(ptrdiff_t __op) volatile _NOEXCEPT {return fetch_sub(__op) - __op;}
```

I think the issue is due to the Marian fork of sentencepiece. The latest version of google/sentencepiece compiles successfully using Xcode 12.5 command-line tools, but marian-nmt/sentencepiece does not. So, the fix might be just to pull in the latest updates from the Google version?

### How to reproduce

Here's the `cmake` command I use to compile Marian (which works with Xcode 12.4 installed).

```
cmake .. -DBUILD_ARCH=x86-64 -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCOMPILE_CPU=on -DCOMPILE_CUDA=off -DCOMPILE_SERVER=on -DUSE_SENTENCEPIECE=on -DUSE_DOXYGEN=off -DUSE_APPLE_ACCELERATE=on
```

I also reproduced the compilation errors in just the marian-nmt/sentencepiece repo via:

```
cmake .. -DCMAKE_OSX_ARCHITECTURES=x86_64
```

### Context

I wasn't 100% sure if this issue was isolated to the marian-nmt/sentencepiece repo, or applied to Marian more broadly, so I opened an issue in this repo. Happy to open an issue in the other repo if that would be better, though.

Thanks!

**Comment by tmacwill** [comment]
Just checked—merging google/sentencepiece into marian-nmt/sentencepiece has no merge conflicts, and enables marian-nmt/sentencepiece to compile successfully on macOS. (Not sure if there are other consequences, though.)

**Comment by dameikle** [comment]
It's the case insenstive file system on macOS causing the issue, resulting in the _include<version>_ of _cstddef_ picking up the VERSION file in the directory.

If you did the following command it should build:
`mv ../src/3rd_party/sentencepiece/VERSION ../src/3rd_party/sentencepiece/VERSION.bak`

The upstream version now calls this VERSION.txt which doesn't have this problem.

**Comment by tmacwill** [comment]
got it, thanks! I can confirm that compiling with the latest macOS no longer gives that error.

fwiw, compilation now errors with the below on the latest macOS and Xcode:

```
/Users/tmac/marian-dev/src/tensors/cpu/fbgemm/expanded_gemm.h:295:8: error: private field 'elementType_' is not used [-Werror,-Wunused-private-field]
  Type elementType_;
```

guessing macOS/Xcode has different defaults for `CFLAGS` / `CXXFLAGS` than other platforms, but would be great if marian either compiled with the stock settings or had a fix listed in the installation instructions. happy to create a new issue for that, but the title of this one still applies, so commenting here.

thanks!

**Comment by dameikle** [comment]
I've opened a PR for the private field warning https://github.com/marian-nmt/marian-dev/pull/872

**Comment by tmacwill** [comment]
awesome, thanks so much!

**Comment by snukky** [comment]
#872 which should solve the issue is merged, so closing.
