### ISSUE TITLE
Compilation error in spdlog with GCC 7

### ISSUE THREAD

**Issue by tomekd** [marian-nmt/marian-dev#83]
Marian doesn't compile with GCC 7 (Arch Linux). The problem occurs in spdlog code. The current master of spdlog has already fixed that problem, so the suggested solution is to update spdlog.

**Comment by emjotde** [comment]
Reopening this because of the revert in #87

**Comment by emjotde** [comment]
@tomekd can you post the compile error here?

**Comment by tomekd** [comment]
No problem.

```
[40/64] Building NVCC (Device) object src/CMakeFiles/marian.dir/graph/marian_generated_expression_operators.cu.o
FAILED: src/CMakeFiles/marian.dir/graph/marian_generated_expression_operators.cu.o 
cd /home/tomaszd/codes/marian-test/build/src/CMakeFiles/marian.dir/graph && /usr/bin/cmake -E make_directory /home/tomaszd/codes/marian-test/build/src/CMakeFiles/marian.dir/graph/. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING= -D generated_file:STRING=/home/tomaszd/codes/marian-test/build/src/CMakeFiles/marian.dir/graph/./marian_generated_expression_operators.cu.o -D generated_cubin_file:STRING=/home/tomaszd/codes/marian-test/build/src/CMakeFiles/marian.dir/graph/./marian_generated_expression_operators.cu.o.cubin.txt -P /home/tomaszd/codes/marian-test/build/src/CMakeFiles/marian.dir/graph/marian_generated_expression_operators.cu.o.cmake
/home/tomaszd/codes/marian-test/src/3rd_party/spdlog/details/format.h(2166): error: expected an identifier
          detected during:
            instantiation of "Result fmt::internal::ArgVisitor<Impl, Result>::visit(const fmt::internal::Arg &) [with Impl=fmt::internal::BasicArgFormatter<char>, Result=void]" 
(4373): here
            instantiation of "const fmt::BasicFormatter<CharType, ArgFormatter>::Char *fmt::BasicFormatter<CharType, ArgFormatter>::format(const fmt::BasicFormatter<CharType, ArgFormatter>::Char *&, const fmt::internal::Arg &) [with CharType=char, ArgFormatter=fmt::internal::BasicArgFormatter<char>]" 
(4397): here
            instantiation of "void fmt::BasicFormatter<CharType, ArgFormatter>::format(fmt::BasicCStringRef<fmt::BasicFormatter<CharType, ArgFormatter>::Char>) [with CharType=char, ArgFormatter=fmt::internal::BasicArgFormatter<char>]" 
(2876): here
            instantiation of "void fmt::BasicWriter<Char>::write(fmt::BasicCStringRef<Char>, fmt::ArgList) [with Char=char]" 
(3657): here

1 error detected in the compilation of "/tmp/tmpxft_00000d75_00000000-7_expression_operators.cpp1.ii".
CMake Error at marian_generated_expression_operators.cu.o.cmake:278 (message):
  Error generating file
  /home/tomaszd/codes/marian-test/build/src/CMakeFiles/marian.dir/graph/./marian_generated_expression_operators.cu.o
```

**Comment by emjotde** [comment]
@tomekd What's the status of this?

**Comment by tomekd** [comment]
checked today. It works with g++ 7.2, boost 1.65 and CUDA 9.

**Comment by emjotde** [comment]
Does cuda compile with gcc 7?

**Comment by tomekd** [comment]
The following command works for me:
```
cmake -DCUDA_HOST_COMPILER=/usr/bin/gcc-5 ..
```

I've just talked with @XapaJIaMnu about problems with cuda 9. We couldn't compile marian using 
``-DCUDA_HOST_COMPILER=/usr/bin/gcc-6``, despite the official notes.

**Comment by emjotde** [comment]
I am asking about gcc 7, so is the issue.

**Comment by XapaJIaMnu** [comment]
CUDA 9 Doesn't support GCC7. It only supports GCC6, but there's a crash when compiling with GCC6, so you need to revert to GCC5. You can compile the CPP only code with GCC-7 but any code compiled with nvcc has to use GCC5 host compiler. Likely they will fix the GCC6 issue very soon, cause it's creeping up on the web...

**Comment by emjotde** [comment]
Which would make this whole issue irrelevant?

**Comment by XapaJIaMnu** [comment]
Yes. It is quite normal for people using cuda with bleeding edge diestros to have two different gccs because you usually want the latest gcc, but cuda is holding you back so you have a second gcc that is passed as a host compiler
